# Site settings
author: Corbin Arnett
title: 
header-img: img/home-bg.png
email: corbin.c.arnett@gmail.com
copyright_name: Corbin Arnett
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: corbinarnett
github_username:  corbinarnett

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
